version: "3.9"
services:
  manager:
    image: apachepulsar/pulsar-manager:v0.2.0
    depends_on:
      - pulsar
    ports:
      - "9527:9527"
      - "7750:7750"
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
    networks:
      - pulsar
  
  # add enviments: http://pulsar:8080
  manager_setup:
    image: curlimages/curl:7.81.0
    depends_on:
      - manager
    restart: "no"
    volumes:
      - ./manager_setup.sh:/manager_setup.sh
    networks:
      - pulsar
    command: [ "./manager_setup.sh" ]
  
  pulsar:
    image: apachepulsar/pulsar:2.8.1
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: bin/pulsar standalone
    volumes:
      - pulsardata:/tmp/pulsar/data
      - pulsarconf:/tmp/pulsar/conf
    networks:
      - pulsar

volumes:
  pulsardata:
  pulsarconf:

networks:
  pulsar: